# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='county',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='county',
            name='short_name',
            field=models.CharField(default='', max_length=100, verbose_name='Short City Name'),
        ),
        migrations.AddField(
            model_name='county',
            name='sort',
            field=models.SmallIntegerField(default=0, verbose_name='Sorting Order'),
        ),
    ]
