# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170207_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.UUIDField(default=None, null=True, verbose_name='Apply User Id')),
                ('apply_user', models.UUIDField(default=None, null=True, verbose_name='Apply User Id')),
                ('company', models.UUIDField(default=None, null=True, verbose_name='Company Id')),
                ('code', models.CharField(default='', max_length=64, null=True, verbose_name='File code')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='File Create Date')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype_name', models.CharField(max_length=32, verbose_name='File type name')),
            ],
        ),
        migrations.CreateModel(
            name='SexType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_type', models.CharField(max_length=8, verbose_name='Sex type name')),
            ],
        ),
        migrations.AddField(
            model_name='filekit',
            name='filetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.FileType'),
        ),
    ]
