# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170209_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='address',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='burst_code',
            field=models.TextField(default='', max_length=32, verbose_name='Burst Code'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='current_status',
            field=models.SmallIntegerField(default=0, verbose_name='Current Status'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='describe',
            field=models.TextField(default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='email',
            field=models.CharField(default='', max_length=45, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='file_kit',
            field=models.UUIDField(default=None, null=True, verbose_name='File Kit Id'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='fullname',
            field=models.CharField(default='', max_length=64, verbose_name='User full name'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='id_card',
            field=models.CharField(default='', max_length=32, verbose_name='User ID card number'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='is_login',
            field=models.BooleanField(default=True, verbose_name='Is login user'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='photo',
            field=models.ImageField(null=True, upload_to=b'', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='reg_status',
            field=models.SmallIntegerField(default=1, verbose_name='Registration Status'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='supervisor_id',
            field=models.UUIDField(default=None, null=True, verbose_name='Supervisor Id'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='telephone',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='Telephone number'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='user_name',
            field=models.CharField(default='', max_length=20, verbose_name='User name'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='work_status',
            field=models.SmallIntegerField(default=1, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_reg_type',
            field=models.CharField(max_length=32, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='departofcompany',
            name='depart_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='user_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='User login id'),
        ),
    ]
