# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170209_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filekit',
            name='filetype',
        ),
        migrations.DeleteModel(
            name='SexType',
        ),
        migrations.DeleteModel(
            name='FileKit',
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
    ]
