# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170209_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='sextype',
            field=models.TextField(default='', max_length=32, null=True, verbose_name='Set type'),
        ),
    ]
