# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sysuser_sextype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysuser',
            old_name='sextype',
            new_name='sex',
        ),
    ]
