# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sysuser_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Is supervisor'),
        ),
    ]
