# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sysuser_is_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='certificate_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CertificateType'),
        ),
    ]
