# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sysuser_certificate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='file_kit',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='supervisor_id',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='Address'),
        ),
    ]
