# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170210_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='file_kit',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='file_name',
        ),
    ]
