# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170211_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='file_kit',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='File Kit'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='file_name',
            field=models.FileField(default='', upload_to='./upload/'),
        ),
    ]
