# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170211_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='file_name',
        ),
    ]
