# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_sysuser_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='file_name',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='File Name'),
        ),
    ]
