# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_messagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetype',
            name='message_type',
            field=models.CharField(max_length=32, verbose_name='Message Type Name'),
        ),
    ]
