# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20170212_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='message_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.MessageType'),
        ),
    ]
