# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_equipmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipemntSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Equipment Type')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EquipmentType')),
            ],
        ),
    ]
