# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_equipemntsubtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(default='', max_length=64, null=True, verbose_name='Equipment name')),
                ('equipment_code', models.CharField(default='', max_length=64, null=True, verbose_name='Equipment code')),
                ('reg_status', models.SmallIntegerField(default=0, verbose_name='Register status')),
                ('work_status', models.SmallIntegerField(default=0, verbose_name='Working status')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('valid_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid time')),
                ('allot_company_id', models.UUIDField(default=uuid.uuid4, verbose_name='Allocation company id')),
            ],
        ),
    ]
