# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Allocation company id'),
        ),
    ]
