# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_equipment_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='company',
        ),
        migrations.AddField(
            model_name='equipment',
            name='company_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Company id'),
        ),
    ]
