# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170213_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipemntSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Equipment Type')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(default='', max_length=64, null=True, verbose_name='Equipment name')),
                ('equipment_code', models.CharField(default='', max_length=64, null=True, verbose_name='Equipment code')),
                ('reg_status', models.SmallIntegerField(default=0, verbose_name='Register status')),
                ('work_status', models.SmallIntegerField(default=0, verbose_name='Working status')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('valid_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid time')),
                ('allot_company_id', models.UUIDField(default=uuid.uuid4, verbose_name='Allocation company id')),
                ('company_id', models.UUIDField(default=uuid.uuid4, verbose_name='Company id')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Equipment Type')),
            ],
        ),
        migrations.AddField(
            model_name='equipemntsubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EquipmentType'),
        ),
    ]
