# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_equipment_equipment_sub_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipemntSubType',
            new_name='EquipmntSubType',
        ),
    ]
