# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20170213_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_sub_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.EquipmntSubType'),
        ),
    ]
