# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_equipment_equipment_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='reg_status',
            field=models.SmallIntegerField(default=2, verbose_name='Register status'),
        ),
    ]
