# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20170213_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='create_time',
        ),
    ]
