# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20170213_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='work_status',
            field=models.SmallIntegerField(default=1, verbose_name='Working status'),
        ),
    ]
