# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20170213_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('name', models.CharField(default='', max_length=64, null=True, verbose_name='Name')),
                ('address', models.CharField(default='', max_length=128, null=True, verbose_name='Addess')),
                ('describe', models.CharField(default='', max_length=256)),
                ('police_company_id', models.CharField(default='', max_length=32, null=True, verbose_name='Police Company Id')),
                ('project_code', models.CharField(default='', max_length=64, null=True, verbose_name='Project Code')),
                ('file_kit_id', models.CharField(default='', max_length=32, null=True, verbose_name='File Kit Id')),
                ('status', models.SmallIntegerField(default=1)),
                ('associate_status', models.SmallIntegerField(default=1)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Latitude')),
                ('radius', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('apply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SysUser')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Province')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', models.CharField(default='', max_length=16, verbose_name='State')),
                ('status', models.CharField(default='', max_length=16, verbose_name='Status')),
                ('lock_mode', models.SmallIntegerField(default=0)),
                ('b_require_select_user', models.BooleanField(default=False)),
                ('comment_type', models.BooleanField(default=False)),
                ('b_can_terminate', models.BooleanField(default=False)),
                ('b_can_translate', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='blastproject',
            name='work_flow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.WorkFlow'),
        ),
    ]
