# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20170214_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('name', models.CharField(default='', max_length=64, null=True, verbose_name='Name')),
                ('describe', models.CharField(default='', max_length=256)),
                ('gps_longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Longitude')),
                ('gps_latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Latitude')),
                ('baidu_longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Baidu Longitude')),
                ('baidu_latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Baidu Latitude')),
                ('radius', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('plan_deto_num', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('plan_explosive_num', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('apply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SysUser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AreaRegStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AreaReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AreaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='reg_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.AreaRegStatus'),
        ),
        migrations.AddField(
            model_name='area',
            name='report_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.AreaReportStatus'),
        ),
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.AreaStatus'),
        ),
        migrations.AddField(
            model_name='area',
            name='work_flow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.WorkFlow'),
        ),
    ]
