# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20170220_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BlastRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('police_company_id', models.CharField(default='', max_length=32, null=True, verbose_name='Police Company Id')),
                ('deto_transfer_record_id', models.CharField(default='', max_length=32, null=True, verbose_name='Deto transfer record Id')),
                ('user1_id', models.CharField(default='', max_length=32, null=True, verbose_name='User1 Id')),
                ('user2_id', models.CharField(default='', max_length=32, null=True, verbose_name='User2 Id')),
                ('blast_auth_user1_id', models.CharField(default='', max_length=32, null=True, verbose_name='Auth User1 Id')),
                ('blast_auth_user2_id', models.CharField(default='', max_length=32, null=True, verbose_name='Auth User2 Id')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('blasting_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Blasting time')),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Latitude')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('blast_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BlastMode')),
            ],
        ),
        migrations.CreateModel(
            name='BlastType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='blastrecord',
            name='blast_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BlastType'),
        ),
        migrations.AddField(
            model_name='blastrecord',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City'),
        ),
        migrations.AddField(
            model_name='blastrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
        migrations.AddField(
            model_name='blastrecord',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County'),
        ),
        migrations.AddField(
            model_name='blastrecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipment'),
        ),
        migrations.AddField(
            model_name='blastrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AddField(
            model_name='blastrecord',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Province'),
        ),
    ]
