# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20170221_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('police_company_id', models.CharField(default='', max_length=32, null=True, verbose_name='Police Company Id')),
                ('supervisor_company_id', models.CharField(default='', max_length=32, null=True, verbose_name='supervisor_company_id')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('sign_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sign in time')),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Latitude')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Province')),
            ],
        ),
        migrations.CreateModel(
            name='SignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='signrecord',
            name='sign_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SignType'),
        ),
        migrations.AddField(
            model_name='signrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SysUser'),
        ),
    ]
