# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20170222_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('police_company_id', models.CharField(default='', max_length=32, null=True, verbose_name='Police Company Id')),
                ('resource_count', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('transport_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='transport_time')),
                ('car_code', models.CharField(default='', max_length=32, null=True, verbose_name='car_code')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Province')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ResourceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SysUser')),
            ],
        ),
    ]
