# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_resourcetype_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MeterialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('main_code', models.CharField(default='', max_length=32, null=True, verbose_name='main_code')),
                ('soc_code', models.CharField(default='', max_length=32, null=True, verbose_name='soc_code')),
                ('produce_code', models.CharField(default='', max_length=32, null=True, verbose_name='produce_code')),
                ('simple_code', models.CharField(default='', max_length=32, null=True, verbose_name='simple_code')),
                ('start_index', models.IntegerField(default=0, null=True)),
                ('end_index', models.IntegerField(default=0, null=True)),
                ('version_id', models.SmallIntegerField(default=0, null=True)),
                ('deto_status', models.SmallIntegerField(default=0, null=True)),
                ('resource_count', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('unit', models.IntegerField(default=0, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('police_company_id', models.CharField(default='', max_length=32, null=True, verbose_name='Police Company Id')),
                ('from_user1_id', models.CharField(default='', max_length=32, null=True, verbose_name='From User1 Id')),
                ('from_user2_id', models.CharField(default='', max_length=32, null=True, verbose_name='From User2 Id')),
                ('to_user2_id', models.CharField(default='', max_length=32, null=True, verbose_name='To User1 Id')),
                ('to_user1_id', models.CharField(default='', max_length=32, null=True, verbose_name='To User2 Id')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('transfer_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='transfer_time')),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Latitude')),
                ('resource_count', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Province')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TransferRecordType'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MaterialType'),
        ),
        migrations.AddField(
            model_name='meterialrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Transfer'),
        ),
        migrations.AddField(
            model_name='meterialrecord',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TransferRecordType'),
        ),
        migrations.AddField(
            model_name='meterialrecord',
            name='resource_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MaterialSubType'),
        ),
        migrations.AddField(
            model_name='meterialrecord',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MaterialType'),
        ),
        migrations.AddField(
            model_name='meterialrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SysUser'),
        ),
    ]
