# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_remove_meterialrecord_resource_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterialrecord',
            name='resource_sub_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.MaterialSubType'),
            preserve_default=False,
        ),
    ]
