# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20170227_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBlastTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('shake_hz_1', models.IntegerField(default=0)),
                ('shake_hz_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedObjectTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('range_x1', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('range_x2', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('range_y1', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('range_y2', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('range_z1', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('range_z2', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
            ],
        ),
    ]
