# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_projectblasttypes_protectedobjecttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsubtype',
            name='prompt',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='materialsubtype',
            name='unit_type',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
