# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_projectcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SysUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SysUser')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCamera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('responsible_person', models.CharField(default='', max_length=32, null=True)),
                ('monitory_point_name', models.CharField(default='', max_length=32, null=True)),
                ('monitory_point_address', models.CharField(default='', max_length=128, null=True)),
                ('camera_manufacturers', models.CharField(default='', max_length=64, null=True)),
                ('contact_phone', models.CharField(default='', max_length=64, null=True)),
                ('camera_code', models.CharField(default='', max_length=32, null=True)),
                ('camera_type', models.CharField(default='', max_length=32, null=True)),
                ('visit_url', models.CharField(default='', max_length=256, null=True)),
                ('login_user_name', models.CharField(default='', max_length=32, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('type', models.IntegerField(default=1, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Province')),
            ],
        ),
    ]
