# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_projectperson_projectsupervisor_videocamera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeterialRecord',
            new_name='MaterialRecord',
        ),
    ]
