# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_normaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='./upload')),
            ],
        ),
    ]
