# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20170312_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='area',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Area'),
        ),
        migrations.AddField(
            model_name='videocamera',
            name='project',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
