# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20170312_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocamera',
            old_name='camera_manufacturers',
            new_name='camera_manufacture',
        ),
        migrations.RenameField(
            model_name='videocamera',
            old_name='monitory_point_address',
            new_name='monitor_point_address',
        ),
        migrations.RenameField(
            model_name='videocamera',
            old_name='monitory_point_name',
            new_name='monitor_point_name',
        ),
    ]
