# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20170312_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='login_password',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
