# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_videocamera_login_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_data', models.TextField(default='', max_length=2048, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SysUser')),
            ],
        ),
    ]
