# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_finfer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finfer',
            new_name='Finger',
        ),
    ]
