# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20170501_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrecord',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TransferRecordType'),
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MaterialType'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TransferRecordType'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MaterialType'),
        ),
    ]
