# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20170501_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='id',
            field=models.SmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
