# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_equipmentmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_mode',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.EquipmentMode'),
        ),
    ]
