# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_equipment_equipment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='plan_dgt_deto_num',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
