# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_area_plan_dgt_deto_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='equipment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Equipment'),
        ),
    ]
