# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_detonatorstatus_digitaldetonator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitaldetonator',
            name='manu_time',
        ),
        migrations.AddField(
            model_name='digitaldetonator',
            name='manu_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Manu Date'),
        ),
        migrations.AlterField(
            model_name='digitaldetonator',
            name='blast_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Blast time'),
        ),
    ]
