# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20170524_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldetonator',
            name='status',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DetonatorStatus'),
        ),
    ]
