# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20170524_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=30)),
                ('success', models.CharField(max_length=10)),
                ('volunteer_no', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Application_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('selected_stu_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Date_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('av_start', models.DateField(max_length=30)),
                ('av_end', models.DateField(max_length=30)),
                ('write_sub_s', models.DateField(max_length=30)),
                ('write_sub_e', models.DateField(max_length=30)),
                ('superintendent_s', models.DateField(max_length=30)),
                ('superintendent_e', models.DateField(max_length=30)),
                ('end_select', models.DateField(max_length=30)),
                ('upload_s', models.DateField(max_length=30)),
                ('upload_e', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Select_num_datem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(max_length=20)),
                ('select_num', models.PositiveIntegerField(max_length=20)),
                ('start_date', models.DateField(max_length=30)),
                ('end_date', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='select_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='select_SysUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('stu_class', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('achieve_year', models.PositiveSmallIntegerField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Institution')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Role')),
            ],
        ),
        migrations.CreateModel(
            name='selectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('files', models.CharField(max_length=64)),
                ('file_position', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stu_introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=30)),
                ('stu_introduction', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=64)),
                ('tea_no', models.CharField(max_length=30)),
                ('introduction', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='select_sysuser',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sex'),
        ),
        migrations.AddField(
            model_name='application',
            name='volunteer_topic_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Topic'),
        ),
    ]
