# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20170731_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='select_sysuser',
            old_name='sex',
            new_name='sex_type',
        ),
        migrations.RenameField(
            model_name='select_sysuser',
            old_name='user_no',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='sex',
            old_name='sex',
            new_name='sex_type',
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='volunteer_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='application_state',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='date_setting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='select_num_datem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='select_num_datem',
            name='select_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='select_num_datem',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='select_role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='select_sysuser',
            name='achieve_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='select_sysuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='select_sysuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Select_Role'),
        ),
        migrations.AlterField(
            model_name='selectfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sex',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stu_introduction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
