# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_auto_20170809_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_addr',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='select_sysuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Select_Role'),
        ),
    ]
