# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_auto_20170813_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_sysuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Select_Role'),
        ),
    ]
