# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_auto_20170813_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sex',
            old_name='sex_type',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='select_sysuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Select_Role'),
        ),
    ]
