# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_auto_20170816_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='select_sysuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Select_Role'),
        ),
    ]
